function F = f_charge_balance(pH,inputPar)
%CHARGE_BALANCE
%    F = CHARGE_BALANCE(H,K13_1,K13_2,KAC_AC,KAC_BU,KAC_IN,KAC_VA,KAC_PRO,KW,SIN,SAC,SBU,SPRO,STIC,SVA,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    04-Nov-2014 15:43:01

%inputPar=[K13_1,K13_2,Kac_ac,Kac_bu,Kac_in,Kac_va,Kac_pro,Kw,Sva,Sbu,Spro,Sac,Stic,SIn,Z];
Kac_tic=inputPar(1);
Kac_ac=inputPar(2);
Kac_bu=inputPar(3);
Kac_in=inputPar(4);
Kac_va=inputPar(5);
Kac_pro=inputPar(6);
Kw=inputPar(7);
Kac_lac=inputPar(8);
Sva=inputPar(9);
Sbu=inputPar(10);
Spro=inputPar(11);
Sac=inputPar(12);
Stic=inputPar(13);
SIn=inputPar(14);
Slac=inputPar(15);
Z=inputPar(16);

H=10^-pH;

F = H+Z-Kw./H+(H.*SIn)./(H+Kac_in)-(Kac_ac.*Sac)./(H+Kac_ac)-(Kac_bu.*Sbu)./(H+Kac_bu)-(Kac_pro.*Spro)./(H+Kac_pro)-(Kac_tic.*Stic)./(H+Kac_tic)-(Kac_va.*Sva)./(H+Kac_va)-...
    (Kac_lac.*Slac)./(H+Kac_lac);
